# filepath: automotive-salah/docker-compose.yml
version: '3.8'







services:



  web:



    build:



      context: .



      dockerfile: deployment/docker/Dockerfile.web



    ports:



      - "3000:3000"



    environment:



      - DATABASE_URL=mongodb://mongodb:27017/automotive-locksmith



      - REDIS_URL=redis://redis:6379



      - API_URL=http://api:4000



    depends_on:



      - api



      - mongodb



      - redis



    restart: unless-stopped







  admin:



    build:



      context: .



      dockerfile: deployment/docker/Dockerfile.admin



    ports:



      - "3001:3000"



    environment:



      - DATABASE_URL=mongodb://mongodb:27017/automotive-locksmith



      - API_URL=http://api:4000



    depends_on:



      - api



      - mongodb



    restart: unless-stopped







  api:



    build:



      context: .



      dockerfile: deployment/docker/Dockerfile.api



    ports:



      - "4000:4000"



    environment:



      - DATABASE_URL=mongodb://mongodb:27017/automotive-locksmith



      - REDIS_URL=redis://redis:6379



      - NODE_ENV=production



    depends_on:



      - mongodb



      - redis



    restart: unless-stopped







  mongodb:



    image: mongo:7



    ports:



      - "27017:27017"



    volumes:



      - mongodb_data:/data/db



    environment:



      - MONGO_INITDB_DATABASE=automotive-locksmith



    restart: unless-stopped







  redis:



    image: redis:7-alpine



    ports:



      - "6379:6379"



    volumes:



      - redis_data:/data



    restart: unless-stopped







  nginx:



    image: nginx:alpine



    ports:



      - "80:80"



      - "443:443"



    volumes:



      - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf



      - ./deployment/nginx/ssl:/etc/nginx/ssl



    depends_on:



      - web



      - admin



      - api



    restart: unless-stopped







volumes:



  mongodb_data:



  redis_data:














